// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e439a85e-68c8-4aa2-87e0-d148f1e1fe28";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onIsAutomaticChange();
void onWaterLevelChange();
void onTemperatureChange();
void onHumidityChange();
void onMotorRelayChange();

String isAutomatic;
float waterLevel;
CloudTemperatureSensor temperature;
CloudRelativeHumidity humidity;
bool motorRelay;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(isAutomatic, READWRITE, ON_CHANGE, onIsAutomaticChange);
  ArduinoCloud.addProperty(waterLevel, READWRITE, ON_CHANGE, onWaterLevelChange);
  ArduinoCloud.addProperty(temperature, READWRITE, 2 * SECONDS, onTemperatureChange);
  ArduinoCloud.addProperty(humidity, READWRITE, 2 * SECONDS, onHumidityChange);
  ArduinoCloud.addProperty(motorRelay, READWRITE, ON_CHANGE, onMotorRelayChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
